### ISSUE TITLE
Unset CSS filters in IE for examples

### ISSUE THREAD

**Issue by jnweaver** [UWMadisonUcomm/uw-ui-toolkit#57]
Either override everywhere we're undoing gradients in the example CSS with `filter: none` as needed or use our own bg-gradient mixin that does not set an IE filter to begin with.

**Comment by plweil** [comment]
Agree; I'd probably go with the latter, if the gradients are similar enough. At least some, if not all, of these filters originate in BS (mixins.less).

**Comment by jnweaver** [comment]
Unset filters for now (46064cfdc39f6c2fd31efe68ea8fef17f29100fa); maybe we'll write our own bg-gradient at some point.
