### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by nblair** [UWMadisonUcomm/uw-ui-toolkit#62]
Instead of publishing maven artifacts just to UW's internal repository, let's publish this artifact to Maven Central instead.

[Sonatype has a guide to help get started](http://central.sonatype.org/pages/ossrh-guide.html). I'll open a JIRA task with them to get started and include @jnweaver. Are there any other individuals we should include with permission to publish? @jhanstra would any one from the MUM team be interested in having authorization?

**Comment by nblair** [comment]
Per discussion with @jnweaver, we'll want to include as part of this task a change to the groupId from edu.wisc.uc to edu.wisc.umark.

**Comment by jhanstra** [comment]
@nblair Tim L and Andrew both said they would like access if possible.

**Comment by nblair** [comment]
@jhanstra can you have both Tim L and Andrew comment on https://issues.sonatype.org/browse/OSSRH-13405?

**Comment by nblair** [comment]
@jnweaver and @jhanstra before Tim L and Andrew can push releases for this project, they'll need writes to push to this project as well. Can you put their github usernames in this thread, and @jnweaver  can you give them push?

Once that's done, wheel on over to #67 and review the incoming changes to the pom.

**Comment by jnweaver** [comment]
Will do as soon as I get their usernames.

**Comment by nblair** [comment]
Woohoo: http://search.maven.org/#artifactdetails%7Cedu.wisc.umark%7Cuw-ui-toolkit%7C0.2.2-RC1%7Cjar

We're probably good to merge, we can handle the outstanding bits about permissions for others out-of-band.

**Comment by jnweaver** [comment]
Cool! Can you correct that one edu.wisc.uc groupId reference in PR #67? Then we can merge that.

**Comment by nblair** [comment]
I'll run the actual 0.2.2 release now.
