### ISSUE TITLE
src folder no longer being delivered by bower

### ISSUE THREAD

**Issue by jhanstra** [UWMadisonUcomm/uw-ui-toolkit#65]
Somehow we lost the src folder with all the less files in it when pulling in the latest version with Bower. I can't identify any ignore statement in bower that would have taken it out. @jnweaver any ideas? Am I missing something?

![image](https://cloud.githubusercontent.com/assets/1919535/5843815/d0b489ae-a174-11e4-96ac-7dfb8ebcf97b.png)

![image](https://cloud.githubusercontent.com/assets/1919535/5843833/fa047fc6-a174-11e4-8ebb-677391dac099.png)

**Comment by jnweaver** [comment]
Hmm, I'm actually seeing src when I just installed it now. And I'm seeing all the other directories that begin ./ I should have looked at that closer. I think the ignore pattern there should be just /examples etc, same as a .gitignore file. But I'm not sure why you're not seeing src.

**Comment by jnweaver** [comment]
Jared, try installing the bowerignore branch and see if that works for you. It's working as expected for me.  You should have dist, src, README and the bower.json file.

Here's a sample bower.json file to use: https://gist.github.com/jnweaver/8125067e4533d29753e8

**Comment by jhanstra** [comment]
I uninstalled and reinstalled uw-ui-toolkit on MyUW and it worked. And yep, I got all the ./ folders too, so that's not the right syntax. The updates in that branch look correct to me.

**Comment by jnweaver** [comment]
Just released 0.2.2 to fix this
