### ISSUE TITLE
.myuw .rounded bugged for buttons

### ISSUE THREAD

**Issue by timlevett** [UWMadisonUcomm/uw-ui-toolkit#93]
If you add `.rounded` to a `.btn`, the button radius of `4px` trumps `.rounded`.  Add `!important` to `.rounded`?

**Comment by jhanstra** [comment]
Yea, I think `!important` is the best way to do this. Changing.

**Comment by jhanstra** [comment]
Should be fixed now.

**Comment by timlevett** [comment]
@jhanstra which PR was this fixed in?

**Comment by timlevett** [comment]
nm, found the commit df84fd4
